#
# This file is part of BDC-DB.
# Copyright (C) 2020 INPE.
#
# BDC-DB is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

[pytest]
addopts = --color=auto --cov=bdc_db --cov-report=term-missing
testpaths = tests